#!/usr/bin/env python3
"""Generate the tray battery-percentage SVG icons.

Produces one SVG per whole-number percentage 0..=100 plus an `unknown`
placeholder, written to ``assets/icons/``. Digits are drawn as plain
seven-segment ``<rect>`` geometry so runtime rasterization needs **no fonts**.

Each SVG uses the literal token ``__FG__`` as the fill color; the Rust runtime
substitutes the real color (white / amber / red / green) based on the battery
threshold and charging state before rasterizing.

The script also (re)generates ``src/icon_data.rs`` with ``include_str!`` entries
so the icons are embedded into the binary.

Usage:  python tools/generate_icons.py
Requires: Python 3.8+
"""

from pathlib import Path

# --- canvas ---------------------------------------------------------------
SIZE = 32          # viewBox is 0 0 SIZE SIZE, rendered at tray resolution
DIGIT_TOP = 5.0
DIGIT_H = 22.0

# Per-digit-count layout: (digit_width, gap_between, stroke_thickness)
LAYOUT = {
    1: (15.0, 0.0, 4.6),
    2: (12.0, 3.5, 4.0),
    3: (8.6, 2.0, 2.8),
}

# Which of the 7 segments (a-g) are lit for each digit.
#   aaa
#  f   b
#  f   b
#   ggg
#  e   c
#  e   c
#   ddd
SEGMENTS = {
    "0": "abcdef",
    "1": "bc",
    "2": "abged",
    "3": "abgcd",
    "4": "fgbc",
    "5": "afgcd",
    "6": "afgedc",
    "7": "abc",
    "8": "abcdefg",
    "9": "abcdfg",
}


def _rect(x, y, w, h):
    return (
        f'<rect x="{x:.2f}" y="{y:.2f}" width="{w:.2f}" height="{h:.2f}" '
        f'rx="{min(w, h) * 0.25:.2f}" fill="__FG__"/>'
    )


def digit_rects(ch, x, y, w, h, t):
    """Return the SVG rects for one seven-segment digit in cell (x,y,w,h)."""
    x2 = x + w
    ym = y + h / 2.0
    half = (h / 2.0) - t * 0.6  # vertical segment length, leaving a small gap
    s = t * 0.15                # horizontal inset so corners don't fuse
    seg = {
        "a": _rect(x + s, y, w - 2 * s, t),
        "d": _rect(x + s, y + h - t, w - 2 * s, t),
        "g": _rect(x + s, ym - t / 2.0, w - 2 * s, t),
        "f": _rect(x, y + s, t, half),
        "b": _rect(x2 - t, y + s, t, half),
        "e": _rect(x, ym + s, t, half),
        "c": _rect(x2 - t, ym + s, t, half),
    }
    lit = SEGMENTS[ch]
    return [seg[c] for c in "abcdefg" if c in lit]


def svg_for_number(value):
    digits = str(value)
    n = len(digits)
    dw, gap, t = LAYOUT[n]
    total_w = n * dw + (n - 1) * gap
    x_start = (SIZE - total_w) / 2.0

    body = []
    for i, ch in enumerate(digits):
        cell_x = x_start + i * (dw + gap)
        body.extend(digit_rects(ch, cell_x, DIGIT_TOP, dw, DIGIT_H, t))
    return _wrap(body)


def svg_unknown():
    """Three dots -> 'searching / unknown'."""
    body = [
        f'<circle cx="{cx}" cy="16" r="2.4" fill="__FG__"/>'
        for cx in (9, 16, 23)
    ]
    return _wrap(body)


def _wrap(body):
    inner = "\n  ".join(body)
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'viewBox="0 0 {SIZE} {SIZE}" width="{SIZE}" height="{SIZE}">\n  '
        f"{inner}\n</svg>\n"
    )


def main():
    root = Path(__file__).resolve().parent.parent
    icons_dir = root / "assets" / "icons"
    icons_dir.mkdir(parents=True, exist_ok=True)

    for value in range(0, 101):
        (icons_dir / f"{value:03d}.svg").write_text(
            svg_for_number(value), encoding="utf-8"
        )
    (icons_dir / "unknown.svg").write_text(svg_unknown(), encoding="utf-8")

    # Emit the Rust embed table.
    lines = [
        "// AUTO-GENERATED by tools/generate_icons.py. Do not edit by hand.",
        "//",
        "// SVG source for the tray battery icons. Each string contains the",
        "// literal token `__FG__` which the renderer replaces with the color",
        "// for the current battery threshold / charging state.",
        "",
        "/// SVG for each battery percentage, indexed 0..=100.",
        "pub static LEVEL_SVGS: [&str; 101] = [",
    ]
    for value in range(0, 101):
        lines.append(f'    include_str!("../assets/icons/{value:03d}.svg"),')
    lines.append("];")
    lines.append("")
    lines.append("/// Placeholder shown when the battery level is unknown.")
    lines.append(
        'pub static UNKNOWN_SVG: &str = include_str!("../assets/icons/unknown.svg");'
    )
    lines.append("")
    (root / "src" / "icon_data.rs").write_text("\n".join(lines), encoding="utf-8")

    print(f"Wrote 101 level icons + unknown.svg to {icons_dir}")
    print(f"Wrote embed table to {root / 'src' / 'icon_data.rs'}")


if __name__ == "__main__":
    main()
